"""add notebook_id to directory

Revision ID: 0d392fb4e4a5
Revises: e249f790d97d
Create Date: 2026-02-20 19:49:41.320364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d392fb4e4a5'
down_revision: Union[str, Sequence[str], None] = 'e249f790d97d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_directory_keys_id'), table_name='directory_keys')
    op.drop_table('directory_keys')
    op.add_column('directory', sa.Column('notebook_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'directory', 'notebook', ['notebook_id'], ['id'], ondelete='CASCADE')
    op.add_column('source', sa.Column('user_id', sa.Integer(), nullable=False))
    op.alter_column('source', 'notebook_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'source', 'directory', ['directory_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'source', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'source', 'notebook', ['notebook_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'source', type_='foreignkey')
    op.drop_constraint(None, 'source', type_='foreignkey')
    op.drop_constraint(None, 'source', type_='foreignkey')
    op.alter_column('source', 'notebook_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('source', 'user_id')
    op.drop_constraint(None, 'directory', type_='foreignkey')
    op.drop_column('directory', 'notebook_id')
    op.create_table('directory_keys',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bookmark_sync_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('directory_keys_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('directory_keys_pkey')),
    sa.UniqueConstraint('bookmark_sync_key', name=op.f('directory_keys_bookmark_sync_key_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('user_id', name=op.f('directory_keys_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_directory_keys_id'), 'directory_keys', ['id'], unique=False)
    # ### end Alembic commands ###
