"""컬럼 오타 수정

Revision ID: 8814e0cf60c9
Revises: e231dd10882d
Create Date: 2026-03-12 14:45:42.455593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8814e0cf60c9'
down_revision: Union[str, Sequence[str], None] = 'e231dd10882d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notebook', sa.Column('pinned', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.drop_column('notebook', 'pined')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notebook', sa.Column('pined', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('notebook', 'pinned')
    # ### end Alembic commands ###
