"""delete user id from source/directory

Revision ID: b929b4c1090b
Revises: d146a7874482
Create Date: 2026-02-27 11:20:46.344624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b929b4c1090b'
down_revision: Union[str, Sequence[str], None] = 'd146a7874482'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alembic_version_data')
    op.drop_index(op.f('ix_page_data_embedding_hnsw'), table_name='page_data', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_page_data_id'), table_name='page_data')
    op.drop_index(op.f('ix_page_data_source_id'), table_name='page_data')
    op.drop_table('page_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_data',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('chunk_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], name=op.f('page_data_source_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('page_data_pkey'))
    )
    op.create_index(op.f('ix_page_data_source_id'), 'page_data', ['source_id'], unique=False)
    op.create_index(op.f('ix_page_data_id'), 'page_data', ['id'], unique=False)
    op.create_index(op.f('ix_page_data_embedding_hnsw'), 'page_data', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_table('alembic_version_data',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_data_pkc'))
    )
    # ### end Alembic commands ###
