"""delete user_id from source and directo
ry

Revision ID: d146a7874482
Revises: 
Create Date: 2026-02-24 16:29:10.064208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd146a7874482'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('directory_user_id_fkey'), 'directory', type_='foreignkey')
    op.drop_column('directory', 'user_id')
    op.add_column('source', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_constraint(op.f('source_user_id_fkey'), 'source', type_='foreignkey')
    op.drop_column('source', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('source_user_id_fkey'), 'source', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('source', 'created_at')
    op.add_column('directory', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('directory_user_id_fkey'), 'directory', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
